use crate::core::ig_core_platform::IG_CORE_PLATFORM;
use crate::gfx::ig_gfx_platform::IG_GFX_PLATFORM::*;

pub enum IG_GFX_PLATFORM {
    IG_GFX_PLATFORM_DEFAULT,
    IG_GFX_PLATFORM_DX,
    IG_GFX_PLATFORM_WII,
    IG_GFX_PLATFORM_DURANGO,
    IG_GFX_PLATFORM_ASPEN,
    IG_GFX_PLATFORM_XENON,
    IG_GFX_PLATFORM_PS3,
    IG_GFX_PLATFORM_OSX,
    IG_GFX_PLATFORM_DX11,
    IG_GFX_PLATFORM_CAFE,
    IG_GFX_PLATFORM_RASPI,
    IG_GFX_PLATFORM_NULL,
    IG_GFX_PLATFORM_ANDROID,
    IG_GFX_PLATFORM_METAL,
    IG_GFX_PLATFORM_WGL,
    IG_GFX_PLATFORM_LGTV,
    IG_GFX_PLATFORM_PS4,
    IG_GFX_PLATFORM_LINUX,
    IG_GFX_PLATFORM_MAX,
}

impl From<IG_CORE_PLATFORM> for IG_GFX_PLATFORM {
    fn from(core_platform: IG_CORE_PLATFORM) -> Self {
        match core_platform {
            IG_CORE_PLATFORM::IG_CORE_PLATFORM_DEFAULT => IG_GFX_PLATFORM_DEFAULT,
            IG_CORE_PLATFORM::IG_CORE_PLATFORM_DEPRECATED => IG_GFX_PLATFORM_NULL,
            IG_CORE_PLATFORM::IG_CORE_PLATFORM_WIN32 => IG_GFX_PLATFORM_DX11,
            IG_CORE_PLATFORM::IG_CORE_PLATFORM_WII => IG_GFX_PLATFORM_WII,
            IG_CORE_PLATFORM::IG_CORE_PLATFORM_DURANGO => IG_GFX_PLATFORM_DURANGO,
            IG_CORE_PLATFORM::IG_CORE_PLATFORM_ASPEN => IG_GFX_PLATFORM_ASPEN,
            IG_CORE_PLATFORM::IG_CORE_PLATFORM_XENON => IG_GFX_PLATFORM_XENON,
            IG_CORE_PLATFORM::IG_CORE_PLATFORM_PS3 => IG_GFX_PLATFORM_PS3,
            IG_CORE_PLATFORM::IG_CORE_PLATFORM_OSX => IG_GFX_PLATFORM_OSX,
            IG_CORE_PLATFORM::IG_CORE_PLATFORM_WIN64 => IG_GFX_PLATFORM_DX11,
            IG_CORE_PLATFORM::IG_CORE_PLATFORM_CAFE => IG_GFX_PLATFORM_CAFE,
            IG_CORE_PLATFORM::IG_CORE_PLATFORM_NGP => IG_GFX_PLATFORM_NULL,
            IG_CORE_PLATFORM::IG_CORE_PLATFORM_MARMALADE => IG_GFX_PLATFORM_NULL,
            IG_CORE_PLATFORM::IG_CORE_PLATFORM_RASPI => IG_GFX_PLATFORM_RASPI,
            IG_CORE_PLATFORM::IG_CORE_PLATFORM_ANDROID => IG_GFX_PLATFORM_ASPEN,
            IG_CORE_PLATFORM::IG_CORE_PLATFORM_ASPEN64 => IG_GFX_PLATFORM_ASPEN,
            IG_CORE_PLATFORM::IG_CORE_PLATFORM_LGTV => IG_GFX_PLATFORM_LGTV,
            IG_CORE_PLATFORM::IG_CORE_PLATFORM_PS4 => IG_GFX_PLATFORM_PS4,
            IG_CORE_PLATFORM::IG_CORE_PLATFORM_WP8 => IG_GFX_PLATFORM_NULL,
            IG_CORE_PLATFORM::IG_CORE_PLATFORM_LINUX => IG_GFX_PLATFORM_LINUX,
            IG_CORE_PLATFORM::IG_CORE_PLATFORM_NX => IG_GFX_PLATFORM_NULL,
            IG_CORE_PLATFORM::IG_CORE_PLATFORM_MAX => IG_GFX_PLATFORM_MAX,
        }
    }
}
