[package]
name = "ig-library"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
phf = "0.11.3"
byteorder = "1.5.0"
walkdir = "2.5.0"
flate2 = "1.1.1" #zlib
lzma-rs = "0.3.0"#annoying lzma library
lz4 = "1.28.1" #lz4
paste = "1.0.15"